title: A brief history of cryptography
description: CS5002, Spring 2022, Prof. Alan Jamieson
sitename: A brief history of cryptography
baseurl: 'https://cryptography.vip'
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
